splash = false
ipc = on

preload = ~/pictures/wallpapers/skeleton.png

wallpaper {
    monitor = 
    path = ~/pictures/wallpapers/skeleton.png
}

wallpaper {
    monitor = 
    path = ~/pictures/wallpapers/skeleton.png
}
