splash = false
ipc = on

preload = ~/Pictures/wallpapers/wallhaven-lywpjl.jpg

wallpaper {
    monitor = 
    path = ~/Pictures/wallpapers/wallhaven-lywpjl.jpg
}

wallpaper {
    monitor = 
    path = ~/Pictures/wallpapers/wallhaven-lywpjl.jpg
}
