splash = false
ipc = on

preload = ~/Pictures/wallpapers/clouds.jpg

wallpaper {
    monitor = 
    path = ~/Pictures/wallpapers/clouds.jpg
}

wallpaper {
    monitor = 
    path = ~/Pictures/wallpapers/clouds.jpg
}
