splash = false
ipc = on

preload = ~/pictures/wallpapers/clouds.jpg

wallpaper {
    monitor = 
    path = ~/pictures/wallpapers/clouds.jpg
}

wallpaper {
    monitor = 
    path = ~/pictures/wallpapers/clouds.jpg
}
