# Font Stuffs
font_size 15.0

# General cursor Config
cursor #BA41B2
cursor_shape block

# Cursor Trail!! (ensure kitty is fully updated)
cursor_trail 15
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 1
cursor_trail_color white
